name: Backend Continuous Integration

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - closed
    branches:
      - main
    paths:
      - "starter/backend/**"

env:
  PYTHON_VERSION: 3.11

jobs:
  lint:
    name: Run lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./starter/backend
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - run: pip install pipenv

      - run: pipenv install

      - run: pipenv run lint

  test:
    name: Run test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./starter/backend
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - run: pip install pipenv

      - run: pipenv install

      - run: pipenv run test

  build:
    name: Build backend
    runs-on: ubuntu-latest
    needs: [lint, test]
    defaults:
      run:
        working-directory: ./starter/backend
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - run: pip install pipenv

      - run: pipenv install

      - name: Build Docker Image
        run: |
          docker build --tag mp-backend:latest .
