name: Terraform Apply

on:
  workflow_dispatch:
  push:
    branches:
      - development

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1        

      - name: Initialize Terraform
        run: |
          cd setup/terraform
          terraform init

      - name: Apply Terraform
        run: |
          cd setup/terraform
          terraform apply -auto-approve

      - name: Output Terraform
        run: |
          cd setup/terraform
          terraform output